### ISSUE TITLE
Is it really unidirectional?

### ISSUE THREAD

**Issue by robwiss** [thephez/data-diode#2]
> Only one of the Tx->Rx pairs is connected so the public side cannot transfer data back to the trusted side.

This isn’t really true at a hardware level. Unless I’m misunderstanding something in the rpi docs the serial Tx and Rx pins are actually GPIO pins therefore the Tx could be used as an input pin and the Rx pin could be used as an output pin. An attacker with software access to both sides could reverse the flow of the diode.

**Comment by thephez** [comment]
Yes, this is a valid point (thus the disclaimer in the project description). This project was primarily a learning tool that I decided to push to Github. I did not really expect anyone to actually look at it :slightly_smiling_face: If I had ever actually used it in a project, the setting was such that if an attacker had software access to the "inside" they would not have needed to interact with the diode to do what they wanted.
